---
collections:
  - name: oracle.oci
  - name: devsec.hardening
    version: 8.6.0
  - name: opitzconsulting.ansible_oracle
    version: 3.5.1
  # - name: https://github.com/Rendanic/ansible-oracle.git
  #   type: git
  #   version: prorahost
