---
collections:
  - name: oracle.oci
  - name: devsec.hardening
    version: 8.8.0
  # - name: opitzconsulting.ansible_oracle
  #   version: 4.2.0
  - name: https://github.com/Rendanic/ansible-oracle.git
    type: git
    version: master
