---
is_sw_source_local: true
oracle_sw_copy: false
oracle_sw_unpack: false

golden_image_dest: /u01/golden

# usind NFS-Server
install_from_nfs: true
nfs_server_sw: ansible-oracle-bastion
nfs_server_sw_path: /sw/oracle
oracle_stage_remote: /sw/oracle
