---

oracle_listeners_config:
  LISTENER:
    home: &listener_home db19-gi-ee
    address:
      - host: "{{ ansible_hostname }}"
        protocol: TCP
        port: 1521

listener_installed:
  - home: *listener_home
    listener_name: LISTENER
    state: present
