---
oracle_install_version_gi: 19.3.0.0
oracle_home_gi: /u01/app/oracle/19/grid

# oracle_install_image_gi: restart_home_19.15.zip

apply_patches_gi: true
gi_patches:
  "{{ gi_patches_config['19.16.0.0.220719'] }}"

# ASMlib Configuration
# device_persistence: asmlib
# oracle_asm_disk_string: ORCL:*

# ASMFD Configuration
device_persistence: asmfd
oracle_asmfd_disk_string: /dev/sd*
oracle_asm_disk_string: AFD:*

oracle_asm_init_dg: data

# Partitons are done with os_oci-Playbook!
partition_devices: false

asm_diskgroups:        # ASM Diskgroups used for DB-storage. Should map to dict asm_storage_layout.
  - diskgroup: data
    state: present
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.rdbms, value: 19.0.0.0.0}
      - {name: compatible.asm, value: "19.0.0.0.0"}
    disk:
      - {device: /dev/sdb1, asmlabel: data01}
  - diskgroup: fra
    state: present
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.rdbms, value: 19.0.0.0.0}
      - {name: compatible.asm, value: "19.0.0.0.0"}
    disk:
      - {device: /dev/sdb2, asmlabel: fra01}
