---
# THis Playbook is temporary until user_data has been fixed

- name: Host configuration for OCI
  hosts: oci
  become: true
  become_user: root
  any_errors_fatal: true
  tasks:
    - name: growpart
      ansible.builtin.command: growpart /dev/sda 2
      ignore_errors: true

    - name: pv
      ansible.builtin.command: pvresize /dev/sda2

    # Block Volume size is 50GB in OCI
    # => split Block Volume in partitions for ASM-Disks to safe storage
    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/sdb
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.size }}"
        state: present
      with_items:
        - number: 1
          start: 0%
          size: 20GiB
        - number: 2
          start: 20GiB
          size: 25GiB
      when:
        - ansible_devices.sdb is defined
